In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Prajwal\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [15]:
#series - 1d labeled Array

s = pd.Series([1,2,3,4,5,6])
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>

In [24]:
#index - is like position ( that fixed ( like on 0th position 1 is stored))

#label - is an named index ( address of an index ) 
# EX:
s = pd.Series([54 , 65 , 85 , 96 ], index=["adam" , "Raj" , "Amit" , "kushal"]) #index is an label that signed the adam = 54
print(s)
print("---" * 5)
print(s["adam"])
print(s["kushal"])

adam      54
Raj       65
Amit      85
kushal    96
dtype: int64
---------------
54
96

In [26]:

#Series Properties
"""
1 . Homogenous 
2 . Vectorized Operations
3 . Handle missing Values with NaN
4 . Mutable values, immutable size

"""


s1 = pd.Series([ 1 , 2 , 3 , 4 , 5])
s2 = pd.Series([10 ,20, 30 , 40 ,50])

print(s1 + s2)   #-> 1 + 10 = 11 , 2 +  20 22 ......

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [31]:


# Dataframe - 2d lablled array
# -----------------Creating Dataframe using Dictinary of list 
info = {
    "name" : ["Rahul" , "Raj" , "Amit" , "keshav"],
    "Age"  : [ 21 , 22 ,24 , 19  ],
    "Cgpa" : [ 9.2 , 9.3 , 8.6 , 5.6],
}

df = pd.DataFrame(info)

print(info)
print("-----"*15)
print(df , type(df))

print(df.index)
print(df.columns)

{'name': ['Rahul', 'Raj', 'Amit', 'keshav'], 'Age': [21, 22, 24, 19], 'Cgpa': [9.2, 9.3, 8.6, 5.6]}
---------------------------------------------------------------------------
     name  Age  Cgpa
0   Rahul   21   9.2
1     Raj   22   9.3
2    Amit   24   8.6
3  keshav   19   5.6 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['name', 'Age', 'Cgpa'], dtype='str')

In [29]:
df

     name  Age  Cgpa
0   Rahul   21   9.2
1     Raj   22   9.3
2    Amit   24   8.6
3  keshav   19   5.6

In [36]:
# --------------------------Creating DataFrames using List of List

df =pd.DataFrame([["Adam", 21] , ["Eve" , 22 ], [ "Bob" , 21]], columns = ["name" , "age"]) 
print(df)

   name  age
0  Adam   21
1   Eve   22
2   Bob   21

In [37]:
df

   name  age
0  Adam   21
1   Eve   22
2   Bob   21

In [48]:

# ----------------------Creating Dataframes using numpy(Numeric python) Array 

import numpy as np

np_arr = np.array([[1, 2 ,3 ] , [ 4 , 5 , 6]])
df1 = pd.DataFrame(np_arr)
df2 = pd.DataFrame(np_arr , columns=[ "A", "B" , "C"] )
print(df1)    #print without using columns name ( by default 0 , 1 , 2)
print( "---" * 15)
print(df2  )  #print using column name as per user

   0  1  2
0  1  2  3
1  4  5  6
---------------------------------------------
   A  B  C
0  1  2  3
1  4  5  6