In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Prajwal\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Prajwal\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Prajwal\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

df = pd.read_csv("employee_data.csv")
print(df , type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [6]:


# DataFrames Method :  for EDA 
  # 1. df.head()  2. df.tail()  3. df.sample()  4. df.info()  5. df.shape   6. df.describe()  7. df.columns  8. df.uniques()
df

print(df.head())     #print starting 5 rows ( by default 5..) 
print("------" * 5)
print(df.head(2))     #print starting 2 rows ( by default 5.. as per paramter 2 )

print("------" * 15)
print(df.tail())     #print last 5 rows (by defautl 5...)
print("------" * 5)
print(df.tail(3))     #print last 5 rows (as per parameter 3)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
------------------------------
   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000
------------------------------------------------------------------------------------------
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
------------------------------
   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [12]:
df.sample()    #Any random value or row print

# as per parameter also generted random values / row 
df.sample(2)

   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000
9  10  Julia   30    Finance   60000

In [13]:
df.info()    # give the summary of our data

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

In [17]:
df.shape          # Return tuple value (immutable) of rows an columns ( like 3 rows 5 column)
# no paramter has passed ()

(10, 5)

In [18]:
df.describe()   # give the stastic data of numeric columns( like mean , max ...etc)

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [20]:
df.columns   #print all column of an csv file

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [23]:
df.nunique()    #print unique data count ( no repeated values ....)

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64