In [9]:
# !pip install pandas
# AQI DataSet
import pandas as pd


df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [2]:
#Selecting the columns

df["city"]
df[["city" , "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [3]:
#selecting the rows (using label and index  - { loc and iloc })


df.loc[0]          # index 0 row data 
df.loc[0:2]       # Slicing -- StrIdx : EndIdx   ( ending index is inclusive ( means include ( if you pass 3 then from start to 3rd row will be print)))

df.iloc[2]
df.iloc[0:2]       # Slicing -- StrIdx : EndIdx   ( ending index is exclusive ( means not include ( if you pass 3 then from start to 2nd row will be print not the 3rd row)))

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [4]:


#Cells  -- ( row , column)

    # row  [    "columns"    ]  
df.loc[0 , ["city", "aqi"]]   # columns in pass in [sqaure brackets]
df.loc[0:2 , ["city", "aqi"]]   # columns in pass in [sqaure brackets]


    #index --- the column value will be in integer (not in string ..) becuase i in iloc is represents index
df.iloc[0 , 2]
df.iloc[0:3 , 2]


# printing Country, city , lat and log using (loc)
df.loc[0 , ["country" , "city" , "latitude" , "longitude"]]
df.loc[0:2 , ["country" , "city" , "latitude" , "longitude"]]



# printing Country, city , lat and log using (iloc)
df.iloc[0 , [ 1, 2 , 3 , 4]]
df.iloc[0:3 , 1:5]  #using Slice

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [5]:


#Selected single Scalar values (using  -- at & iat)
    
df.at[0 , "city"]    #0th row and column city

df.iat[0,2]          # 0th row and city (index == 2)

'New York'

In [6]:



df["city"]          # is created a view not an copy
cities=df["city"]
cities[0]  = "mumbai"    # that changes occured in original file 
 #  if you do changes in views  it will also occured in the original file 

# for that reason use .copy()   
    # it created the copy not doing changes in original file
df["city"].copy()

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [7]:


#Filtering our data


df[ df ["aqi"] > 100]
df[ (df ["aqi"] > 100)  & (df["temperature"] > 30) ]   #filtering using the operators


aqi_data = [df[ (df ["aqi"] > 100)  & (df["temperature"] > 30) ] [["city" , "aqi"]]]
aqi_data

[           city  aqi
 6      New York  155
 7      New York  115
 14     New York  121
 17     New York  127
 25     New York  113
 ...         ...  ...
 17947    Zurich  107
 17950    Zurich  140
 17975    Zurich  111
 17976    Zurich  146
 17991    Zurich  104

 [2384 rows x 2 columns]]

In [10]:



# using Query method

df[ df ["aqi"] > 100] # instead of doing this we use query method 


# like
df.query("aqi > 100")


#rules 
    # - Expression as string ( pass the condition in string )
    # - column based Referance  ( directly wrote column name in condition)
    # - use Backticks for col_name with space or special chars
    # - Operators ( &, | , ~, >= , <= , == ,etc...)
    # - @ to referance Python vars  ( for using any value as variable in conditions)
    # - Chained Comparisons ( multiple condition in one )


df.query("aqi > 100  & temperature > 30") [["city" , "aqi"]]

# using @ variable in condition 

aqi_value = 100 
df.query("aqi > @aqi_value  & temperature > 30") [["city" , "aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]