In [1]:


#cleaning our data
"""
1 . Handling missing values 
     - isnull() / isna()
     - isnull().sum()
     - dropna()
     - fillna(value)
     - ffill()
     - bfill()
"""

'\n1 . Handling missing values \n     - isnull() / isna()\n     - isnull().sum()\n     - dropna()\n     - fillna(value)\n     - ffill()\n     - bfill()\n'

In [7]:
import pandas as pd

df = pd.read_csv("raw_data.csv")


df.isnull()    # missing value - returns True
df.isna()    # missing value - returns True


df.isnull().sum()  #count the missing values in column


df.dropna()    #Drop that missing value row from table


df.fillna(0)   #stored all empty value as 0 ( not zero actually that you pass in paramter )


df.ffill()   # forward fill  -> stored a preivous value in empty space ( like 1 , , 2 , 3)
                                            #output -  ( 1 , 1 , 2 , 3 )     ------>

df.bfill()   # backward fill -> stored a last value in empty space ( like 1 , , 2 , 3)
                                            #output -  ( 1 , 2, 2 , 3 )       <-------


# df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [4]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
# Handle Duplicted Values

"""
1. dupilcated()
2. drop_dupilcates()
"""


df.duplicated()  #check Deuplicated row ---> return True

df["country"].duplicated()  #checks for speicfic rows   ---> return True

df.drop_duplicates()         # Deleted Duplicated rows
df.drop_duplicates(inplace=True)         # changes in original data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [ ]:
# Handling Data Types and Date Time 
"""

1. dtypes()
2. astype( newType )
3. to_datetime()
"""

In [12]:
df.dtypes         # showed the data type of columns

id           int64
name           str
age        float64
country        str
gender         str
income     float64
dtype: object

In [ ]:
df._datetime()  # comverting complex timestamp values in date time data

df.astype(newType)   # changing their data type

In [ ]:
#Handling Strings

"""
1. str.lower() , str.upper() & capitalizes()
2. str.strip()      -- > removed extra Spaces
3. str.split(")     ---> split the vlaue ( different )
4. str.contains(val, case=False)     --> value present or not in data
"""

In [17]:


df["gender"].str.lower()    # stored column value in lowercase
df["gender"].str.upper()    # stored column value in uppercase
df["gender"].str.capitalize()    # stored column value in capitalized ( first latter capital )


df["name"].str.split(" ")   # john doe   -- > [ joh  , Doe]


df["country"].str.contains["india", case=False ]

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object